# defaults:
# - env
_target_: rl.ppo_core.KspaceMaskedActorCritic_MT
action_space: ???
observation_space: dummy
dataset: ${env.dataset}
image_shape: ${env.image_shape}
dropout: 0.0
dropout_extra: False
using_init: True
feature_dim: 256
mt_shape: [180]
  
  

