envname: acdc_env
ignore_kspace: False
ignore_image: False
dev_mode: False
val_shuffle: False
num_workers: 3
image_shape: [256, 256]
kspace_shape: [256, 256]
in_channels: 1
scale_reward: True
penalty_factor: -1
delay_step: 7
parallel_init: True
train_fixed_budget: False
eval_fixed_budget: True
batch_size: ???
val_batch_size: 400
test_batch_size: 160
observation_space: [1, 256, 256]
use_weighted_sampler: True

train_path: /******/train
val_path: /******/val
